// Datasets are generated by the pipeline into public/data/ and fetched at
// runtime, so a data refresh never touches the JS bundle.

export async function loadData<T>(file: string): Promise<T> {
  const url = new URL(`data/${file}`, document.baseURI);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Couldn't load ${file} (HTTP ${res.status})`);
  return (await res.json()) as T;
}

/** Replace the page's lede with an error so a failed load isn't a blank map. */
export function showLoadError(err: unknown): void {
  console.error(err);
  const lede = document.getElementById("lede");
  if (lede) lede.textContent = "The map data didn't load. Try reloading the page.";
}

export const escapeHtml = (s: string): string =>
  s.replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);
